### ISSUE TITLE
Error when using rex CLI (None type)

### ISSUE THREAD

**Issue by Merovex** [akshaybabloo/release-exporter#43]
```
GitHub detected. 

Traceback (most recent call last):
  File "/usr/local/bin/rex", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/release_exporter/cli.py", line 107, in main
    cli(obj={})
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/release_exporter/cli.py", line 49, in markdown
    file_type='markdown').write_markdown()
  File "/usr/local/lib/python3.7/site-packages/release_exporter/formatter.py", line 34, in write_markdown
    md_file.writelines(self._converter())
  File "/usr/local/lib/python3.7/site-packages/release_exporter/formatter.py", line 51, in _converter
    self.total_number_tags = sum(1 for k in temp if k['node']['tag']['name'])
  File "/usr/local/lib/python3.7/site-packages/release_exporter/formatter.py", line 51, in <genexpr>
    self.total_number_tags = sum(1 for k in temp if k['node']['tag']['name'])
```

**Comment by akshaybabloo** [comment]
Is your repository public? I'll try it from my end

**Comment by Merovex** [comment]
Sorry, no need to link to the repo in question. I did a little digging into the release_exporter repo and dumped `temp` in formater.py:50 and got the following:

```
[{'node': {'createdAt': '2019-07-06T21:56:17Z',
           'description': '## Changes\n'
                          '\n'
                          '- chore: Working on drafted releases @Merovex '
                          '(#14)\n'
                          '- Hasty Commit: 2019-07-06 17:46:28 @Merovex (#13)\n'
                          '- Playing with drafter @Merovex (#12)\n',
           'name': 'v0.3.0',
           'tag': None}},
 {'node': {'createdAt': '2019-07-06T21:26:11Z',
           'description': 'Creating a release baseline to start tracking '
                          'progress.',
           'name': 'Cleaned up README',
           'tag': {'name': 'v0.2.0'}}},
 {'node': {'createdAt': '2019-03-16T20:21:03Z',
           'description': '',
           'name': 'v0.1',
           'tag': {'name': 'v0.1'}}}]
```

I had a draft release that was not yet tagged. Therefore, the tag was `None`. When I deleted that draft and re-ran the code, I got...

```
[{'node': {'createdAt': '2019-07-06T21:26:11Z',
           'description': 'Creating a release baseline to start tracking '
                          'progress.',
           'name': 'Cleaned up README',
           'tag': {'name': 'v0.2.0'}}},
 {'node': {'createdAt': '2019-03-16T20:21:03Z',
           'description': '',
           'name': 'v0.1',
           'tag': {'name': 'v0.1'}}}]
+-----------------+-----------------+
| Provider        | github.com      |
+-----------------+-----------------+
| Repository Name | *************** |
+-----------------+-----------------+
| Number of Tags  | 2               |
+-----------------+-----------------+
```

There may be a more resilient way to count number of entries, screen out draft releases, or perhaps try-catch formatter.py:51?

**Comment by akshaybabloo** [comment]
Will do that. Thanks

**Comment by berteodosio** [comment]
So, shouldn't a warning / limitation be added to README.md stating that draft releases are not supported? I had the same problem here, and the same solution worked.

By the way thanks for the rex tool, it's very useful :)

**Comment by akshaybabloo** [comment]
> So, shouldn't a warning / limitation be added to README.md stating that draft releases are not supported? I had the same problem here, and the same solution worked.
> 
> By the way thanks for the rex tool, it's very useful :)

Thanks for using the tool, @berteodosio. I am working on a new tool that should be out soon. Will put the limitation on readme
